export const homeData = [
    {
        id:1,
        title: "Avatar",
        released: "18 Dec 2009",
        time:"162 min",
        genres: "Action, Adventure, Fantasy",
        rating:"7.9",
        actors: "Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang",
        plot: "A paraplegic marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
        poster: "https://images.theconversation.com/files/500899/original/file-20221214-461-22jr1l.jpg?ixlib=rb-1.1.0&rect=0%2C7%2C2500%2C1250&q=45&auto=format&w=1356&h=668&fit=crop",
        video:'/avatar.mp4',
        year:'2009',
        embedId:'d6xdV8VAqBY',
    },
    {
        id:2,
        title: "Assassin's Creed",
        released: "21 Dec 2016",
        time:"180 min",
        genres: "Action, Adventure, Fantasy",
        rating:"4.2",
        actors: "Michael Fassbender, Michael Kenneth Williams, Marion Cotillard, Jeremy Irons",
        plot:"When Callum Lynch explores the memories of his ancestor Aguilar and gains the skills of a Master Assassin, he discovers he is a descendant of the secret Assassins society." ,
        poster:"https://staticctf.ubisoft.com/J3yJr34U2pZ2Ieem48Dwy9uqj5PNUQTn/449BBgnc3Q1ha2IN9rh3bR/234dfb6f242b302e411a172816e71286/ACEC_Keyart_00_00_00_mobile.jpg",
        video:'/assassin.mp4',
        year:'2016',
        embedId:'-pUhraVG7Ow',
    },
    {
        id:3,
        title:"Interstellar", 
        released: "07 Nov 2014",
        time:"169 min",
        genres:"Adventure, Drama, Sci-Fi" ,
        rating: "8.6",
        actors: "Ellen Burstyn, Matthew McConaughey, Mackenzie Foy, John Lithgow",
        plot: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
        poster:"https://www.thestreambible.com/wp-content/uploads/2021/11/interstellarmovie-1637822356314-9139.jpg",
        video:'/interstellar.mp4',
        year:'2014',
        embedId:'Lm8p5rlrSkY',
    },
    {
        id:4,
        title:"The Avengers", 
        released: "04 May 2012",
        time:"143 min",
        genres: "Action, Sci-Fi, Thriller",
        rating: "8.1",
        actors: "Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth",
        plot:  "Earth's mightiest heroes must come together and learn to fight as a team if they are to stop the mischievous Loki and his alien army from enslaving humanity.",
        poster: "https://www.pluggedin.com/wp-content/uploads/2019/12/the-avengers-review-image.jpg",
        video:'/avegers.mp4' ,
        year:'2012',
        embedId:'TcMBFSGVi1c'
    }
]

export const upcome= [ 
    {
        id:5,
        title: "Rogue One: A Star Wars Story",
        time:"2h 29min",
        poster: "https://thecinephiliac.files.wordpress.com/2016/12/cwq_ccexuauhczm.jpg",
        genres:'Sci-fi, Action',
        year:'2016',
        rating:'7.8',
        actors:'Felicity Jones, Diego Luna, Ben Mendelsohn',
        released:'December 10, 2016',
        plot:"In a time of conflict, a group of unlikely heroes band together on a mission to steal the plans to the Death Star, the Empire's ultimate weapon of destruction."
    },
    {
        id:6,
        title: "Narcos",
        time:"1h 34min",
        poster:"https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p11993086_b_v13_ag.jpg",
        genres:'Drama ',
        year:'2015',
        rating:'8.8',
        actors:'Wagner Moura, Boyd Holbrook, Pedro Pascal',
        released:'September 1 2018',
        plot:'A chronicled look at the criminal exploits of Colombian drug lord Pablo Escobar, as well as the many other drug kingpins who plagued the country through the years.'
    },
    {
        id:7,
        title:"Gotham", 
        time:"1h 15min",
        poster:"https://static.dc.com/dc/files/default_images/TVPage_Thumb_Gotham_6345b806b1e5b2.56683543.jpg",
        genres:'Action ',
        year:'2014',
        rating:'7.8',
        actors:'Ben McKenzie, Donal Logue, David Mazouz, Robin Lord',
        released:'September 22, 2014',
        plot:"The story behind Detective James Gordon's rise to prominence in Gotham City in the years before Batman's arrival."
    },
    {
        id:8,
        title:"Vikings", 
        time:"2h 50min",
        poster: "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p9155926_b_v10_au.jpg",
        genres:'Drama, Action',
        year:'2013',
        rating:'8.5',
        actors:'Travis Fimmel, Katheryn Winnick, Clive Standen',
        released:'March 3, 2013',
        plot:'Vikings transports us to the brutal and mysterious world of Ragnar Lothbrok, a Viking warrior and farmer who yearns to explore--and raid--the distant shores across the ocean.'
    },
    {
        id:9,
        title:"Doctor Strange", 
        time:"3h 21min",
        poster: "https://e0.pxfuel.com/wallpapers/144/187/desktop-wallpaper-dr-strange-top-65-best-dr-strange-background-doctor-strange-neon-thumbnail.jpg",
        genres:'Action, Adventure',
        year:'2016',
        rating:'7.5',
        actors:'Benedict Cumberbatch, Chiwetel Ejiofor,Rachel McAdams',
        released:'October 13, 2016',
        plot:'While on a journey of physical and spiritual healing, a brilliant neurosurgeon is drawn into the world of the mystic arts.'
    }
]

export const recommended= [ 
    {
        id:10,
        title: "Luke Cage",
        time:"1h 45min",
        poster: "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/715a2c1f-271d-4dde-af5e-db2733e8fc57/d6010w4-86a7210d-0ceb-4de5-a6e5-0534a90986d4.jpg/v1/fill/w_648,h_960,q_75,strp/luke_cage_official_movie_poster_by_mattiasfahlberg_d6010w4-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9OTYwIiwicGF0aCI6IlwvZlwvNzE1YTJjMWYtMjcxZC00ZGRlLWFmNWUtZGIyNzMzZThmYzU3XC9kNjAxMHc0LTg2YTcyMTBkLTBjZWItNGRlNS1hNmU1LTA1MzRhOTA5ODZkNC5qcGciLCJ3aWR0aCI6Ijw9NjQ4In1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.lPIJe3P-YVBZ_Loz-OV0DBElMeKT0KUamZrvtODpAho",
        genres:'Drama',
        year:'2016',
        rating:'7.3',
        actors:'Archie Goodwi, George Tuska, Roy Thomas,John Romita Sr.',
        released:'Fri, Jun 22, 2018',
        plot:'When a sabotaged experiment gives him super strength and unbreakable skin, Luke Cage becomes a fugitive attempting to rebuild his life in Harlem and must confront his past and fight a battle for the heart of his city.'
    },
    {
        id:11,
        title: "Breaking Bad",
        time:"2h 22min",
        poster:"https://upload.wikimedia.org/wikipedia/en/thumb/8/87/Breaking_Bad_season_3_DVD.png/250px-Breaking_Bad_season_3_DVD.png",
        genres:'Drama ',
        year:'2008',
        rating:'9.5',
        actors:'Bryan Cranston, Anna Gunn, Aaron Paul, Betsy Brandt',
        released:'January 20, 2008',
        plot:"A chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine with a former student in order to secure his family's future."
    },
    {
        id:12,
        title:"I Am Legend", 
        time:"1h 56min",
        poster:"https://mattsmorton.files.wordpress.com/2015/07/i-am-legend-2007.jpg",
        genres:'Drama, Sci-fi',
        year:'2007',
        rating:'7.2',
        actors:'Will Smith, Alice Braga, Dash Mihok',
        released:'December 14, 2007',
        plot:'Years after a plague kills most of humanity and transforms the rest into monsters, the sole survivor in New York City struggles valiantly to find a cure.'
    },
    {
        id:13,
        title:"Game of Thrones", 
        time:"2h 15min",
        poster: "https://assets-prd.ignimgs.com/2022/01/14/gameofthrones-allseasons-sq-1642120207458.jpg",
        genres:'Drama ',
        year:'2011',
        rating:'9.2',
        actors:' Peter Dinklage, Lena Headey, Emilia Clarke, Kit Harington',
        released:'April 17, 2011',
        plot:'Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for a millennia.'
    },
    {
        id:14,
        title:"300", 
        time:"2h 55min",
        poster: "https://c8.alamy.com/comp/2JH2PB7/gerard-butler-poster-300-2006-2JH2PB7.jpg",
        genres:'Drama, Action',
        year:'2006',
        rating:'7.6',
        actors:'Gerard Butler,  Lena Headey, David Wenham, Dominic West',
        released:'December 9, 2006',
        plot:'King Leonidas of Sparta and a force of 300 men fight the Persians at Thermopylae in 480 B.C.'
    }
]

export const trending = [
    {
        id:15,
        title: "Pain & Gain",
        released: "26 Apr 2013",
        time:"129 min",
        genres: "Action, Comedy, Crime, Drama",
        rating:"6.4",
        actors: "Mark Wahlberg, Dwayne Johnson, Anthony Mackie, Tony Shalhoub",
        plot: "A trio of bodybuilders in Florida get caught up in an extortion ring and a kidnapping scheme that goes terribly wrong.",
        poster: "https://www2.bfi.org.uk/sites/bfi.org.uk/files/news/pain-%26-gain-2013-002-explosion-behind-trio_1000x750.jpg",
        video:"/pain.mp4",
        year:'2013',
        embedId:'X4orHp2y2ZQ'
    },
    {
        id:16,
        title: "The Irishman",
        released: "7 Nov 2019",
        time:"209 min",
        genres: "Biography, Crime, Drama",
        rating:"8.2",
        actors: "Robert De Niro, Al Pacino, Joe Pesci, Harvey Keitel",
        plot:"A mob hitman recalls his possible involvement with the slaying of Jimmy Hoffa." ,
        poster:"https://moviemovesme.com/wp-content/uploads/2022/03/14511-the-irishman.jpg",
        video:"/irishman.mp4",
        year:'2019',
        embedId:'aaQ6tHK4yq8',
    },
    {
        id:17,
        title:"Marriage Story", 
        released: "06 Dec 2019",
        time:"137 min",
        genres:"Comedy, Drama, Romance" ,
        rating: "8.1",
        actors: "Adam Driver, Scarlett Johansson, Julia Greer, Azhy Robertson",
        plot: "Noah Baumbach's incisive and compassionate look at a marriage breaking up and a family staying together.",
        poster:"https://angelusnews.com/wp-content/uploads/2020/01/Marriage_Story-1024x796.jpg",
        video:"/marriage.mp4",
        year:'2019',
        embedId:'G1WbuZ7iQM8',
    },
    {
        id:18,
        title:"Little Women", 
        released: "25 Dec 1994",
        time:"115 min",
        genres: "Drama, Family, Romance",
        rating: "7.3",
        actors: "Winona Ryder, Gabriel Byrne, Trini Alvarado, Samantha Mathis",
        plot:  "The March sisters live and grow in post-Civil War America.",
        poster: "https://www.hollywoodreporter.com/wp-content/uploads/2020/01/little_women_still.jpg?w=1296",
        video:"/woman.mp4",
        year:'1994',
        embedId:'vYSN8Uey4e0'
    }
]

export const latest= [ 
    {
        id:19,
        title: "They Shall Not Grow Old",
        time:"1h 33min",
        poster:"https://resizing.flixster.com/-qmFIMHLJMCwaZ07zhtOrlJJCR8=/300x300/v2/https://resizing.flixster.com/VvFDDPvaXPXAA4xu2jK0n6DFi-s=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzE0YmRkNzgxLTczYmQtNDdkOC1hMzYxLWFjODc0NWVhZmFiNy53ZWJw",
        genres:'Documentary, War',
        year:'2018',
        rating:'8.2',
        actors:'-',
        released:'16 October 2018',
        plot:'A documentary about World War I with never-before-seen footage to commemorate the centennial of the end of the war.'
        
    },
    {
        id:20,
        title:"Once Upon a Time... in Hollywood", 
        time:"2h 41min",
        poster: "https://reelyberniecom.files.wordpress.com/2019/07/once-upon-time-hollywood-movie-posters.jpg",
        genres:'Drama, Comedy',
        year:'2019',
        rating:'7.6',
        actors:'Leonardo DiCaprio, Brad Pitt, Margot Robbie',
        released:'May 21, 2019',
        plot:"A faded television actor and his stunt double strive to achieve fame and success in the final years of Hollywood's Golden Age in 1969 Los Angeles."
    },
    {
        id:21,
        title:"Midnight Family", 
        time:"1h 21min",
        poster:"https://m.media-amazon.com/images/M/MV5BMGYyZTk5MjYtNGY2ZS00NzRhLTgwMWMtZjhmMmQ4OGFkNTNiXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg",
        genres:'Action, Crime, Drama ',
        year:'2019',
        rating:'7.4',
        actors:'Fer Ochoa, Josue Ochoa, Juan Ochoa',
        released:'26 January 2019',
        plot:"In Mexico City's wealthiest neighborhoods, the Ochoa family runs a private ambulance, competing with other for-profit EMTs for patients in need of urgent help."
    },   
     {
        id:22,
        title: "Dolemite Is My Name",
        time:"1h 58min",
        poster: "https://compote.slate.com/images/a7716e61-7503-48e2-9481-25bad2ab6ee0.jpeg?crop=1560%2C1040%2Cx0%2Cy0",
        genres:'Drama, Comedy',
        year:'2019',
        rating:'7.2',
        actors:'Eddie Murphy, Keegan-Michael Key, Mike Epps',
        released:'September 7, 2019',
        plot:"Eddie Murphy portrays real-life legend Rudy Ray Moore, a comedy and rap pioneer who proved naysayers wrong when his hilarious, obscene, kung-fu fighting alter ego, Dolemite, became a 1970s Blaxploitation phenomenon."
    },
]

export const series=[
    {
        id:23,
        title:'Superman & Lois',
        season:'Season 3',
        genres:'Action ',
        year:'2021',
        rating:'7.8',
        time:'1h 21min',
        actors:'Tyler Hoechlin, Elizabeth Tulloch, Jordan Elsass',
        released:'February 23, 2021',
        plot:"The world's most famous superhero and comic books' most famous journalist face the pressures and complexities that come with balancing work, justice, and parenthood in today's society.",
        poster:'https://media.comicbook.com/2021/03/superman-and-lois-poster-1259202.jpeg?auto=webp&width=533&height=800&crop=533:800,smart'
    },
    {
        id:24,
        title:'Fubar',
        season:'Season 1',
        genres:'Action, Comedy',
        year:'2021',
        time:'1h 21min',
        rating:'6.5',
        actors:'Arnold Schwarzenegger, Monica Barbaro, Milan Carter',
        released:'May 25, 2023',
        plot:'A C.I.A. operative on the edge of retirement discovers a family secret and is called back into the field for one last job.',
        poster:'https://flxt.tmsimg.com/assets/p24169012_b_v13_ab.jpg'
    },
    {
        id:25,
        title:'Mayor of Kingstown',
        season:'Season 2',
        genres:'Thriller ',
        year:'2021',
        rating:'8.2',
        time:'1h 21min',
        actors:'Jeremy Renner, Dianne Wiest, Hugh Dillon, Tobi Bamtefa',
        released:'November 14, 2021',
        plot:"The McLusky family are power brokers tackling themes of systemic racism, corruption and inequality in Kingstown, Michigan, where the business of incarceration is the only thriving industry.",
        poster:'https://pyxis.nymag.com/v1/imgs/0a1/e14/2906e00ac7151520d2fc65bc362476b2a7-mayor-of-kingstown-poster.rvertical.w330.jpg'
    },
    {
        id:26,
        title:'Citadel',
        season:'Season 1',
        genres:'Action, Drama, Thriller ',
        year:'2023',
        rating:'6.1',
        time:'1h 21min',
        actors:'Richard Madden, Priyanka Chopra Jonas, Stanley Tucci',
        released:'April 28, 2023',
        plot:"Global spy agency Citadel has fallen, and its agents' memories were wiped clean. Now the powerful syndicate, Manticore, is rising in the void. Can the Citadel agents recollect their past and summon the strength to fight back?",
        poster:'https://pbs.twimg.com/media/FtNlK0uWIAEIzuv.jpg'
    },
    {
        id:27,
        title:'The Tailor',
        season:'Season 1',
        genres:'Drama, Mystery, Thriller',
        year:'2023',
        rating:'6.2',
        time:'1h 21min',
        actors:'Çağatay Ulusoy, Şifanur Gül, Salih Bademci, Olgun Şimşek',
        released:'2 May 2023',
        plot:"A famous tailor begins to sew a wedding dress for his best friend's fiance- but all three have dark secrets that will soon upend their lives.",
        poster:'https://www.themoviedb.org/t/p/original/b4oZzRsD5VOWbxRPdKJf9lCUfav.jpg'
    },
    {
        id:28,
        title:'Power Book II',
        season:'Season 1',
        genres:'Crime, Drama',
        year:'2020',
        rating:'7.5',
        time:'',
        actors:'Michael Rainey Jr., Shane Johnson, Gianni Paolo',
        released:'September 6, 2020',
        plot:"The journey of some of Power's most controversial characters.",
        poster:'https://cdn.cinematerial.com/p/297x/alo9srjq/power-book-ii-ghost-movie-poster-md.jpg?v=1634318889'
    },
    {
        id:29,
        title:'The Flash',
        season:'Season 9',
        genres:'Drama, Action',
        year:'2023',
        rating:'7.5',
        time:'1h 21min',
        actors:'Ezra Miller, Sasha Calle, Michael Shannon, Ron Livingston',
        released:'June 12, 2023',
        plot:"After being struck by lightning, Barry Allen wakes up from his coma to discover he's been given the power of super speed, becoming the Flash, and fighting crime in Central City.",
        poster:'https://rukminim1.flixcart.com/image/850/1000/kyvvtzk0/poster/a/z/a/medium-the-flash-barry-allen-superhero-television-series-matte-original-imagbyg6yamfmzt9.jpeg?q=90'
    },
    {
        id:30,
        title:'Black Bird',
        season:'Season 1',
        genres:'Crime, Drama',
        year:'2022',
        rating:'8.1',
        time:'1h 21min',
        actors:'Taron Egerton, Paul Walter Hauser, Sepideh Moafi, Greg Kinnear',
        released:'August 5, 2022',
        plot:"Jimmy Keene is sentenced to 10 years in a minimum security prison but he cuts a deal with the FBI to befriend a suspected serial killer. Keene has to elicit a confession from Larry Hall to find the bodies of as many as eighteen women.",
        poster:'https://m.media-amazon.com/images/I/51aoUL0zZcL._AC_UF894,1000_QL80_.jpg'
    },
    {
        id:31,
        title:'Black Night',
        season:'Season 1',
        genres:'Drama,Sci-fi, Action, Adventure',
        year:'2022',
        rating:'6.4',
        time:'1h 21min',
        actors:'Kim Woo-bin, Song Seung-heon, Kang You-Seok, Esom',
        released:'5 June 1970',
        plot:"A legendary delivery driver '5-8' with exceptional battle skills And a refugee 'Sawol' who dreams of following in his footsteps.",
        poster:'https://br.web.img2.acsta.net/pictures/23/04/27/00/50/1123940.jpg'
    },
    {
        id:32,
        title:'Titans',
        season:'Season 4',
        genres:'Action, Adventure, Drama',
        year:'2018',
        rating:'7.5',
        time:'1h 21min',
        actors:'Brenton Thwaites, Anna Diop, Teagan Croft',
        released:'October 12, 2018',
        plot:'Dick and Rachel, a girl possessed by a strange darkness, get embroiled in a conspiracy that could bring Hell on Earth. Joining them along the way are the hot-headed Starfire and lovable Beast Boy. Together they become a team of heroes.',
        poster:'https://i.pinimg.com/1200x/16/10/2a/16102a5178781743b1d5a3372454ad93.jpg'
    },
    {
        id:33,
        title:'Queen Charlotte',
        season:'Season 1',
        genres:'Drama, History',
        year:'2023',
        rating:'7.4',
        time:'1h 21min',
        actors:'India Amarteifio, Adjoa Andoh, Michelle Fairley',
        released:'May 4, 2023',
        plot:"Betrothed against her will to King George, young Charlotte arrives in London on her wedding day and faces scrutiny from the monarch's cunning mother.",
        poster:'https://dnm.nflximg.net/api/v6/ALnfVbMvPhqZAIuQMLkxmdJcXYk/AAAAQe--EeItvWy4LZsZp_-zxSuDYByKHly74oVwD3r673JqOQTd7h2oP98BJORTtyiOzJTyMZ3zd212hC4rsH_GT92kz8lsnDev9TRzJJwU8WoC4utC5niEAlS3rYw_avQMi6sl32-ebXYA_52RIYpuEWFPaFN1XTauuod4hrEz1ZtDIDa7oGj3tP_4k7dA-RcuETI_IaNiXF3Gfr3gci1xDRFRUEdZfseUcC6tmyFKN00lcyJyq5QQdY8MwghGWuZ-pmsa8-McrcLI3_ua-Q.jpg?r=201'
    },
    {
        id:34,
        title:'Kaleidoscope',
        season:'Season 1',
        genres:'Action, Crime, Drama, Thriller',
        year:'2023',
        rating:'6.6',
        time:'1h 21min',
        actors:'Giancarlo Esposito, Rufus Sewell, Paz Vega',
        released:'January 1, 2023',
        plot:"Centered around the largest heist ever attempted, the vengeance and betrayals that surround it.",
        poster:'https://i.pinimg.com/736x/cd/9d/c9/cd9dc9381799a992f1a97db01f7d1c1f.jpg'
    },
    {
        id:35,
        title:'Absentia',
        season:'Season 3',
        genres:'Crime, Drama, Mystery, Thriller',
        year:'2017',
        rating:'7.2',
        time:'1h 21min',
        actors:'Stana Katic, Patrick Heusinger, Neil Jackson, Paul Freeman',
        released:'September 25, 2017',
        plot:"After being declared dead in absentia, an FBI agent must reclaim her family, identity and innocence when she finds herself the prime suspect in a string of murders.",
        poster:'https://i.pinimg.com/1200x/e3/1e/25/e31e258ffab6244a701365a742a1835b.jpg'
    },
    {
        id:36,
        title:'Snowfall',
        season:'Season 4',
        genres:'Crime, Drama',
        year:'2017',
        rating:'8.3',
        time:'1h 21min',
        actors:'Damson Idris, Carter Hudson, Emily Rios',
        released:'July 5, 2017',
        plot:'A look at the early days of the crack cocaine epidemic in Los Angeles during the beginning of the 1980s.',
        poster:'https://flxt.tmsimg.com/assets/p19256281_b_v13_ac.jpg'
    },
    {
        id:37,
        title:'The Mandalorian',
        season:'Season 3',
        genres:'Action, Adventure, Fantasy, Sci-Fi',
        year:'2019',
        rating:'8.7',
        time:'1h 21min',
        actors:'Pedro Pascal, Katee Sackhoff',
        released:'November 12, 2019',
        plot:"The travels of a lone bounty hunter in the outer reaches of the galaxy, far from the authority of the New Republic.",
        poster:'https://lumiere-a.akamaihd.net/v1/images/image_30d95723.jpeg'
    },
    {
        id:38,
        title:'Young Royals',
        season:'Season 2',
        genres:'Genres, Drama, Romance',
        year:'2021',
        rating:'8.3',
        time:'1h 21min',
        actors:'Edvin Ryding, Omar Rudber, Malte Gårdinger',
        released:'1 July 2021',
        plot:'Prince Wilhelm adjusts to life at his prestigious new boarding school, Hillerska, but following his heart proves more challenging than anticipated.',
        poster:'https://www.crew-united.com/Media/Images/1418/1418775/1418775.entity.jpg'
    },
    {
        id:39,
        title:'Taxi Driver',
        season:'Season 2',
        genres:'Crime, Drama',
        year:'2021',
        rating:'8.2',
        time:'1h 21min',
        actors:'Robert De Niro, Jodie Foster, Cybill Shepherd, Harvey Keitel',
        released:'February 9, 1976',
        plot:"A mentally unstable veteran works as a nighttime taxi driver in New York City, where the perceived decadence and sleaze fuels his urge for violent action.",
        poster:'https://upload.wikimedia.org/wikipedia/en/9/99/Taxi_Driver_TV_series.jpg'
    },
    {
        id:40,
        title:'Tehran',
        season:'Season 2',
        genres:'Action, Crime, Drama, Thriller',
        year:'2020',
        rating:'7.6',
        time:'1h 21min',
        actors:'Niv Sultan, Shaun Toub, Shervin Alenabi, Yoalah Brinson',
        released:'June 22, 2020',
        plot:"A Mossad agent embarks on her first mission as a computer hacker in her home town of Tehran.",
        poster:'https://foreignpolicy.com/wp-content/uploads/2020/09/Tehran_Apple-TV-key_art_SW_V1.jpg?w=1500'
    },
    {
        id:41,
        title:'Sky High',
        season:'Season 1',
        genres:'Action, Adventure, Crime, Thriller',
        year:'2005',
        rating:'6.3',
        time:'1h 21min',
        actors:'Kelly Preston, Michael Angarano, Danielle Panabaker',
        released:'July 29, 2005',
        plot:"Set in an era where superheroes are commonly known and accepted, young William Stronghold, the son of the Commander and Jetstream, tries to find a balance between being a normal teenager and an extraordinary being.",
        poster:'https://flixpatrol.com/runtime/cache/files/posters/h/ha3mabxteqlf09cfsgcgaa2dpy7.webp'
    },
    {
        id:42,
        title:'The Night Agent',
        season:'Season 1',
        genres:'Action, Thriller, Drama ',
        year:'2023',
        rating:'7.5',
        time:'1h 21min',
        actors:'Gabriel Basso, Luciane Buchanan, Fola Evans-Akingbola',
        released:'	March 23, 2023',
        plot:"Low-level FBI agent Peter Sutherland works in the basement of the White House manning a phone that never rings - until the night it does, propelling him into a conspiracy that leads all the way to the Oval Office.",
        poster:'https://images-s.kinorium.com/movie/poster/2705555/w1500_51652102.jpg'
    }
]